"""initial migration

Revision ID: 8527fb41af05
Revises: 
Create Date: 2023-07-22 21:59:54.914956

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8527fb41af05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE SCHEMA IF NOT EXISTS content;
ALTER ROLE app SET search_path TO content,public;
CREATE EXTENSION "uuid-ossp";""")
    op.create_table('users',
                    sa.Column('username', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password_hash', sa.String(length=512), nullable=False),
                    sa.Column('first_name', sa.String(length=255), nullable=True),
                    sa.Column('last_name', sa.String(length=255), nullable=True),
                    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content'
                    )
    op.create_index(op.f('ix_content_users_email'), 'users', ['email'], unique=True, schema='content')
    op.create_index(op.f('ix_content_users_username'), 'users', ['username'], unique=True, schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_users_username'), table_name='users', schema='content')
    op.drop_index(op.f('ix_content_users_email'), table_name='users', schema='content')
    op.drop_table('users', schema='content')
    # ### end Alembic commands ###
