version: '3'
services:
  db:
    container_name: db-wbtr
    image: postgres:13.0-alpine
    volumes:
      - postgres_data-wbtr:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

#  app:
#    container_name: app
#    build: ./app/
#    volumes:
#      - media_volume-wbtr:/opt/app/src/media/
#    env_file:
#      - .env
#    depends_on:
#      - db
#      - redis
#
#  nginx:
#    container_name: nginx-wbtr
#    image: nginx:1.23.3
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/configs:/etc/nginx/conf.d:ro
#      - media_volume-wbtr:/var/www/media/
#    depends_on:
#      - app
#    ports:
#      - "80:80"

  redis:
    container_name: redis-wbtr
    image: redis
    restart: on-failure

volumes:
  postgres_data-wbtr:
  media_volume-wbtr: